### ISSUE TITLE
checklist items to report

### ISSUE THREAD

**Issue by mpadge** [ropenscilabs/pkgcheck#9]
Items currently listed in [Stat Software Review Book](https://ropenscilabs.github.io/statistical-software-review-book/pkgsubmission.html#bot-checks-executed-on-initial-submission):

- [x] `srr_stats_pre_submit()` must confirm that all standards have been addressed, and that a “Life Cycle Statement” has been included within the CONTRIBUTING.md document.
- [x] `R CMD check` must generate no errors, and all warnings must be explained.
- [x] All tests must pass
- [x] Test coverage must be at least ~~70%~~ 75% (as per [*Dev Guide*](https://devguide.ropensci.org/building.html#testing))
- [x] The package must use `roxygen2` to generate documentation.
- [x] No function should have cyclomatic complexity of 15 or greater
- [x] The package must contain at least one vignette
- [x] The package must be documented on an associated website
- [x] [`pkgstats`](https://github.com/mpadge/pkgstats) report
- [x] no tab-spacing used in code
- [x] git  hash with link to that point in repo

**Comment by maelle** [comment]
* Presence of CITATION (probably hard to check it's not the boilerplate one?)
* Presence of codemeta.json
* available::available() (not as a green/red light, as the package with the name on CRAN/Bioconductor might be the same package as the one under review)

**Comment by maelle** [comment]
From available I'm not sure I'd expect to see anything about offensiveness.

**Comment by maelle** [comment]
Spell check via spelling?

**Comment by mpadge** [comment]
> Spell check via spelling?

Yes, it can be done, but i don't think that is particularly actionable unless we insist that `inst/WORDLIST`  be included in repos. And i personally would be against recommending that. So we'd likely end up with a huge dump of technical words for each submission. One thing that would be useful would be to require a `Language` field in the description, so at least we'd know what kind of spell check to apply. Thoughts?

**Comment by maelle** [comment]
@noamross should we move the spell checking from "editor checks" to something we suggest in the author guide?

**Comment by noamross** [comment]
Yes, makes sense.

**Comment by maelle** [comment]
Now done!

**Comment by mpadge** [comment]
@maelle `available` is kinda broken these days, but we can easily just do the most important checks of
1. Whether it already exists on CRAN/bioc; and
2. use `.standard_regexps()$valid_package_name` (which i did not previously know about, and which is all they do anyway).

I'll implement those and add an additional `"package name is available"` checklist item

**Comment by maelle** [comment]
sounds good, thank you!

**Comment by mpadge** [comment]
All of these checks are now implemented. Next (closing) commit will document up front which checks are actually conducted
